### ISSUE TITLE
how to run in production

### ISSUE THREAD

**Issue by constantinosergiou** [newaeonweb/Hands-On-Full-Stack-Web-Development-with-Angular-6-and-Laravel-5#1]
Basically we the angular app will run in example.com
but laravel api ... where it shoud run ? proper way in the same domain ....
how can this done? 

thank you

**Comment by newaeonweb** [comment]
Hello @constantinosergiou , sorry for may delay. Complete instructions on how to build in production, you can find at chapter 11. Thanks
