### ISSUE TITLE
pdo_mysql not working in chapter-04 

### ISSUE THREAD

**Issue by ajmalhsn** [newaeonweb/Hands-On-Full-Stack-Web-Development-with-Angular-6-and-Laravel-5#2]
I have followed the books instruction but while executing DB::connection()->getPdo(); I am getting an exception of driver is not found

**Comment by jackyhjj** [comment]
I am having the same problem, please advise.

**Comment by ajmalhsn** [comment]
Dear Sir,

I have modified the DockerFile as per the suggestion from different people(stackOverflow and Github issues). Having said that I also checked the ini setting present in php-fpm container, pdo-mysql was commented. This is a link to my DockerFile which has small modification enabling pdo-mysql. I have encountered another problem but it is with swagger. I have no idea how swagger works but have used it in my internship for documenting Rest API. The same is mentioned in this book but it doesn’t seem to comply. It would be really appreciating if you could update the repo based on changes made.
https://github.com/ajmalhsn/chapter-04/blob/master/phpdocker/php-fpm/Dockerfile

Thanking You,
Ajmal


From: Jacky
Sent: 10 July 2019 05:12 PM
To: newaeonweb/Hands-On-Full-Stack-Web-Development-with-Angular-6-and-Laravel-5
Cc: Ajmal Hussain; Author
Subject: Re:[newaeonweb/Hands-On-Full-Stack-Web-Development-with-Angular-6-and-Laravel-5]pdo_mysql not working in chapter-04 (#2)

I am having the same problem, please advise.

**Comment by newaeonweb** [comment]
pull request are always welcome, thanks
